version: '3.7'
services:
  web-vuln:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"
  ftp-server:
    image: stilliard/pure-ftpd
    ports:
      - "2121:21"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
